### ISSUE TITLE
Ensure we don't double-notify exceptions in `after_rollback` or `after_commit`

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-ruby#179]
Rails 4.2 no longer swallows exceptions raised in `after_rollback` or `after_commit` callbacks, we should check if our special handling of these (`Bugsnag::Rails::ActiveRecordRescue`) will cause any problems in rails 4.2.

**Comment by lowensk** [comment]
It doesn't appear that this will be an issue, because Bugsnag::Rails::ActiveRecordRescue monkey patches a method called run_callbacks. Note the following caller output for 4.1.8:

```
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in `block in make_lambda'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:253:in `call'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:253:in `block in simple'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/Users/keegan/code/bugsnag-ruby/lib/bugsnag/rails/active_record_rescue.rb:11:in `run_callbacks'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:296:in `committed!'
```

In 4.2, active_support/callbacks.rb has changed its internal behavior:


```
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:260:in `call'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:260:in `block in simple'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_commit_callbacks'
/Users/keegan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:314:in `committed!'
```

Note that that in 4.2.0 the call to `run_callbacks` has been replaced with a call to `_run_commit_callbacks`, which then calls  `_run_callbacks` — if in a future version, the internal implementation went back to using a method named `run_callbacks`, we would have to worry about the double-notify issue.

**Comment by loopj** [comment]
yay!
